import { type FormEvent, useEffect, useState } from 'react';
import { adminGet, adminPost, adminPut } from './api';
import { Preloader } from '../shared/components/Preloader';
import { RequestState } from '../shared/components/RequestState';

interface Provider { id:number; slug:string; name:string; status:'enabled'|'disabled'; }
interface Field { key:string; label:string; type:'text'|'toggle'; required:boolean; description:string|null; value:string; group:string; }
interface Form { provider:string; configured:boolean; fields:Field[]; }

export function LemonSqueezyWorkspace(){
  const [provider,setProvider]=useState<Provider|null>(null);const [configuration,setConfiguration]=useState<Form|null>(null);const [values,setValues]=useState<Record<string,string>>({});const [saved,setSaved]=useState<Record<string,string>>({});const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);
  const load=async()=>{setError(null);try{const providers=await adminGet<Provider[]>('providers');const item=providers.data.find(candidate=>candidate.slug==='lemonsqueezy')??null;setProvider(item);if(!item)return;const form=await adminGet<Form>(`providers/${item.id}/configuration`);setConfiguration(form.data);const next=Object.fromEntries(form.data.fields.map(field=>[field.key,String(field.value??'')]));setValues(next);setSaved(next);}catch(reason){setError(reason instanceof Error?reason.message:'Lemon Squeezy settings could not be loaded.');}};
  useEffect(()=>{void load();},[]);
  const enabled=values.purchase_verification_enabled==='1';
  const customExpiryEnabled=values.custom_support_expiry_enabled==='1';
  const save=async(event:FormEvent)=>{event.preventDefault();if(!provider)return;setSaving(true);setError(null);setNotice(null);try{const response=await adminPut<Form>(`providers/${provider.id}/configuration`,{settings:values});if(enabled&&provider.status!=='enabled'){await adminPost(`providers/${provider.id}/enable`,{});setProvider({...provider,status:'enabled'});}const next=Object.fromEntries(response.data.fields.map(field=>[field.key,String(field.value??'')]));setConfiguration(response.data);setValues(next);setSaved(next);setNotice('Lemon Squeezy settings saved.');}catch(reason){setError(reason instanceof Error?reason.message:'Lemon Squeezy settings could not be saved.');}finally{setSaving(false);}};
  if(error&&!configuration)return <RequestState compact title="Lemon Squeezy settings unavailable" message={error} retry={()=>void load()}/>;
  if(!provider)return <RequestState compact title="Lemon Squeezy integration unavailable" message="Reload this page after updating SupportBay so the integration can be provisioned."/>;
  if(!configuration)return <Preloader label="Loading Lemon Squeezy settings…" compact/>;
  const enableField=configuration.fields.find(field=>field.key==='purchase_verification_enabled');
  const detailFields=configuration.fields.filter(field=>field.key!=='purchase_verification_enabled');
  const toggle=(field:Field)=><label className="sbay-general-toggle" key={field.key}><input type="checkbox" role="switch" checked={values[field.key]==='1'} disabled={saving} onChange={event=>setValues({...values,[field.key]:event.target.checked?'1':'0',...(field.key==='custom_support_expiry_enabled'&&event.target.checked?{check_support_expiry:'1'}:{})})}/><span aria-hidden="true"/><strong>{field.label}</strong></label>;
  const input=(field:Field)=>field.key==='custom_support_expiry_unit'?<label className="sbay-general-select" key={field.key}><span>Duration Unit</span><select className="sbay-status-select" aria-label="Duration Unit" disabled={saving} value={values[field.key]??'years'} onChange={event=>setValues({...values,[field.key]:event.target.value})}><option value="days">Days</option><option value="months">Months</option><option value="years">Years</option></select></label>:<label className="sbay-general-select" key={field.key}><span>{field.label}{field.required?' *':''}</span><input type={field.key==='custom_support_expiry_amount'?'number':'text'} min={field.key==='custom_support_expiry_amount'?1:undefined} required={field.required} disabled={saving} value={values[field.key]??''} onChange={event=>setValues({...values,[field.key]:event.target.value})}/>{field.description?<small>{field.description}</small>:null}</label>;
  const visibleDetailFields=detailFields.filter(field=>!['custom_support_expiry_amount','custom_support_expiry_unit'].includes(field.key)||customExpiryEnabled);
  return <section className="sbay-integration-settings"><header><small>License-key purchase integration</small><h2>Lemon Squeezy</h2><p>Validate customer license keys before allowing support tickets.</p></header>{notice?<p className="sbay-admin-success">{notice}</p>:null}{error?<p className="sbay-admin-error">{error}</p>:null}<div className="sbay-envato-settings-card"><form onSubmit={save}><div className="sbay-envato-login-settings">{enableField?toggle(enableField):null}{enabled?visibleDetailFields.map(field=>field.type==='toggle'?toggle(field):input(field)):null}</div><footer className="sbay-general-actions"><button disabled={saving||JSON.stringify(values)===JSON.stringify(saved)}>{saving?'Saving…':'Save Changes'}</button><button type="button" disabled={saving||JSON.stringify(values)===JSON.stringify(saved)} onClick={()=>setValues(saved)}>Discard</button></footer></form></div></section>;
}
