import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { RichTextEditor } from '../shared/editor/RichTextEditor';
import { adminDelete, adminGet, adminPost, adminPut } from './api';

interface SavedReply { id:number;title:string;content:string;category:string|null;department_id:number|null;status:'active'|'inactive';usage_count:number;last_used_at:string|null;last_used_by:number|null;updated_at:string }
interface Placeholder { key:string;label:string }
interface Department { id:number;name:string }
const empty={id:0,title:'',content:'',category:null,department_id:null,status:'active' as const,usage_count:0,last_used_at:null,last_used_by:null,updated_at:''};

export function SavedReplyWorkspace() {
  const [items,setItems]=useState<SavedReply[]>([]);
  const [selected,setSelected]=useState<SavedReply>(empty);
  const [query,setQuery]=useState('');
  const [sort,setSort]=useState<'title'|'usage'|'recent'>('title');
  const [category,setCategory]=useState('');
  const [department,setDepartment]=useState('');
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [error,setError]=useState<string|null>(null);
  const [notice,setNotice]=useState<string|null>(null);
  const [placeholders,setPlaceholders]=useState<Placeholder[]>([]);
  const [departments,setDepartments]=useState<Department[]>([]);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const [active,inactive,departmentResponse]=await Promise.all([adminGet<SavedReply[]>('saved-replies?status=active'),adminGet<SavedReply[]>('saved-replies?status=inactive'),adminGet<Department[]>('departments?status=active')]);setItems([...active.data,...inactive.data].sort((a,b)=>a.title.localeCompare(b.title)));setDepartments(departmentResponse.data);if(Array.isArray(active.meta.placeholders))setPlaceholders(active.meta.placeholders as Placeholder[]);}catch(reason){setError(reason instanceof Error?reason.message:'Saved replies could not be loaded.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const categories=useMemo(()=>Array.from(new Set(items.map(item=>item.category).filter((value):value is string=>Boolean(value)))).sort(),[items]);
  const visible=useMemo(()=>items.filter(item=>(!category||item.category===category)&&(!department||(department==='global'?item.department_id===null:item.department_id===Number(department)))&&`${item.title} ${item.content.replace(/<[^>]*>/g,' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='usage'?b.usage_count-a.usage_count||a.title.localeCompare(b.title):sort==='recent'?(Date.parse(b.last_used_at||'')||0)-(Date.parse(a.last_used_at||'')||0)||a.title.localeCompare(b.title):a.title.localeCompare(b.title)),[items,query,sort,category,department]);
  const save=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError(null);setNotice(null);try{const payload={title:selected.title,content:selected.content,category:selected.category,department_id:selected.department_id,status:selected.status};const response=selected.id?await adminPut<SavedReply>(`saved-replies/${selected.id}`,payload):await adminPost<SavedReply>('saved-replies',payload);setSelected(response.data);setNotice(selected.id?'Saved reply updated.':'Saved reply created.');await load();}catch(reason){setError(reason instanceof Error?reason.message:'Saved reply could not be saved.');}finally{setSaving(false);}};
  const remove=async()=>{if(!selected.id||!window.confirm(`Delete “${selected.title}”? This cannot be undone.`))return;setSaving(true);setError(null);try{await adminDelete(`saved-replies/${selected.id}`);setSelected(empty);setNotice('Saved reply deleted.');await load();}catch(reason){setError(reason instanceof Error?reason.message:'Saved reply could not be deleted.');}finally{setSaving(false);}};

  return <section className="sbay-saved-reply-settings">
    <header><div><small>Agent productivity</small><h2>Saved Replies</h2><p>Create reusable, sanitized responses for replies and internal notes.</p></div><button type="button" onClick={()=>{setSelected(empty);setError(null);setNotice(null);}}>Add Saved Reply</button></header>
    {error?<p className="sbay-admin-error" role="alert">{error}</p>:null}{notice?<p className="sbay-admin-success" role="status">{notice}</p>:null}
    <div className="sbay-saved-reply-settings__grid"><aside><label>Search<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search saved replies…"/></label><label>Category<select value={category} onChange={event=>setCategory(event.target.value)}><option value="">All Categories</option>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>Department scope<select value={department} onChange={event=>setDepartment(event.target.value)}><option value="">All Scopes</option><option value="global">Global</option>{departments.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Sort<select value={sort} onChange={event=>setSort(event.target.value as typeof sort)}><option value="title">Title</option><option value="usage">Most Used</option><option value="recent">Recently Used</option></select></label>{loading?<p>Loading…</p>:visible.length===0?<p>No saved replies found.</p>:<ul>{visible.map(item=><li key={item.id}><button type="button" className={selected.id===item.id?'is-active':''} onClick={()=>{setSelected(item);setNotice(null);setError(null);}}><strong>{item.title}</strong><span>{item.category?`${item.category} · `:''}{item.department_id?`Department #${item.department_id} · `:'Global · '}{item.status} · {item.usage_count} uses</span></button></li>)}</ul>}</aside>
      <form onSubmit={save}><label>Title<input required maxLength={190} value={selected.title} onChange={event=>setSelected(current=>({...current,title:event.target.value}))}/></label><label>Category<input maxLength={100} value={selected.category??''} onChange={event=>setSelected(current=>({...current,category:event.target.value||null}))} placeholder="For example: Billing"/></label><label>Department scope<select value={selected.department_id??''} onChange={event=>setSelected(current=>({...current,department_id:Number(event.target.value)||null}))}><option value="">Global — all departments</option>{departments.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Status<select value={selected.status} onChange={event=>setSelected(current=>({...current,status:event.target.value as SavedReply['status']}))}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>{selected.id?<div className="sbay-saved-reply-usage"><span><strong>{selected.usage_count}</strong> composer insertions</span><span>{selected.last_used_at?`Last inserted ${new Date(selected.last_used_at).toLocaleString()} by user #${selected.last_used_by}`:'Not inserted yet'}</span></div>:null}<label>Reply content</label><div className="sbay-saved-reply-placeholders" aria-label="Saved reply placeholders">{placeholders.map(item=><button type="button" key={item.key} title={`Insert ${item.label}`} onClick={()=>setSelected(current=>({...current,content:`${current.content}{{${item.key}}}`}))}>{`{{${item.key}}}`}</button>)}</div><RichTextEditor key={selected.id||'new'} value={selected.content} onChange={content=>setSelected(current=>({...current,content}))} disabled={saving}/><div className="sbay-saved-reply-settings__actions"><button disabled={saving||selected.title.trim()===''||selected.content.trim()===''}>{saving?'Saving…':selected.id?'Save Changes':'Create Saved Reply'}</button>{selected.id?<button type="button" className="is-danger" disabled={saving} onClick={()=>void remove()}>Delete</button>:null}</div></form>
    </div>
  </section>;
}
