import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Preloader } from '../shared/components/Preloader';
import { adminGet, adminPut } from './api';

interface SecuritySettings {recaptcha_v3_enabled:boolean;recaptcha_v3_site_key:string;recaptcha_v3_secret_key:string;recaptcha_v3_secret_configured:boolean;recaptcha_v3_show_login:boolean;recaptcha_v3_show_guest_ticket:boolean;recaptcha_v3_show_registration:boolean;recaptcha_v3_hide_badge:boolean;}
type Draft=Omit<SecuritySettings,'recaptcha_v3_secret_configured'>;
const draftFrom=(s:SecuritySettings):Draft=>({recaptcha_v3_enabled:s.recaptcha_v3_enabled,recaptcha_v3_site_key:s.recaptcha_v3_site_key,recaptcha_v3_secret_key:'',recaptcha_v3_show_login:s.recaptcha_v3_show_login,recaptcha_v3_show_guest_ticket:s.recaptcha_v3_show_guest_ticket,recaptcha_v3_show_registration:s.recaptcha_v3_show_registration,recaptcha_v3_hide_badge:s.recaptcha_v3_hide_badge});
export function SecurityWorkspace(){
 const [settings,setSettings]=useState<SecuritySettings|null>(null),[draft,setDraft]=useState<Draft|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 useEffect(()=>{adminGet<SecuritySettings>('settings/general').then(r=>{setSettings(r.data);setDraft(draftFrom(r.data));}).catch(e=>setError(e instanceof Error?e.message:'Security settings could not be loaded.'));},[]);
 const changed=useMemo(()=>settings&&draft?JSON.stringify(draft)!==JSON.stringify(draftFrom(settings)):false,[settings,draft]);const update=(c:Partial<Draft>)=>setDraft(v=>v?{...v,...c}:v);const discard=()=>{if(settings)setDraft(draftFrom(settings));setError(null);setNotice(null);};
 const save=async(e:FormEvent)=>{e.preventDefault();if(!draft||!changed)return;setSaving(true);setError(null);setNotice(null);try{const r=await adminPut<SecuritySettings>('settings/general',draft);setSettings(r.data);setDraft(draftFrom(r.data));setNotice('Security settings saved.');}catch(reason){setError(reason instanceof Error?reason.message:'Security settings could not be saved.');}finally{setSaving(false);}};
 if(!settings||!draft)return <section className="sbay-security-settings"><Preloader label="Loading security settings…" /></section>;const valid=!draft.recaptcha_v3_enabled||(draft.recaptcha_v3_site_key.trim()!==''&&(draft.recaptcha_v3_secret_key.trim()!==''||settings.recaptcha_v3_secret_configured));
 return <section className="sbay-security-settings"><header><small>Abuse protection</small><h2>Security</h2></header>{error?<p className="sbay-admin-error" role="alert">{error}</p>:null}{notice?<p className="sbay-admin-success" role="status">{notice}</p>:null}<form onSubmit={save}><nav><strong>reCAPTCHA (v3)</strong></nav><div className="sbay-security-main"><label className="sbay-general-toggle"><input type="checkbox" role="switch" disabled={saving} checked={draft.recaptcha_v3_enabled} onChange={e=>update({recaptcha_v3_enabled:e.target.checked})}/><span>{draft.recaptcha_v3_enabled?'Click to disable.':'Click to enable.'}</span></label><label className="sbay-general-select"><span><i>*</i> Site Key</span><input type="text" autoComplete="off" disabled={saving||!draft.recaptcha_v3_enabled} value={draft.recaptcha_v3_site_key} onChange={e=>update({recaptcha_v3_site_key:e.target.value})}/></label><label className="sbay-general-select"><span><i>*</i> Secret Key <span className="sbay-setting-help" tabIndex={0}>?<span role="tooltip">Stored encrypted. Leave blank to keep the configured secret.</span></span></span><input type="password" autoComplete="new-password" disabled={saving||!draft.recaptcha_v3_enabled} value={draft.recaptcha_v3_secret_key} placeholder={settings.recaptcha_v3_secret_configured?'Configured — enter to replace':''} onChange={e=>update({recaptcha_v3_secret_key:e.target.value})}/></label><fieldset disabled={saving||!draft.recaptcha_v3_enabled}><legend>Display Options</legend><label><input type="checkbox" checked={draft.recaptcha_v3_show_login} onChange={e=>update({recaptcha_v3_show_login:e.target.checked})}/> Show in Login Form</label><label><input type="checkbox" checked={draft.recaptcha_v3_show_guest_ticket} onChange={e=>update({recaptcha_v3_show_guest_ticket:e.target.checked})}/> Show in Ticket Form (If not logged in)</label><label><input type="checkbox" checked={draft.recaptcha_v3_show_registration} onChange={e=>update({recaptcha_v3_show_registration:e.target.checked})}/> Show in Registration Form</label></fieldset><label className="sbay-general-toggle"><input type="checkbox" role="switch" disabled={saving||!draft.recaptcha_v3_enabled} checked={draft.recaptcha_v3_hide_badge} onChange={e=>update({recaptcha_v3_hide_badge:e.target.checked})}/><span>Hide reCAPTCHA Badge.</span></label><footer className="sbay-general-actions"><button type="submit" disabled={saving||!changed||!valid}>{saving?'Saving…':'Save Changes'}</button><button type="button" disabled={saving||!changed} onClick={discard}>Discard</button></footer></div></form></section>;
}
