import type {WorkspaceMode,WorkspaceTicket} from './types';

export function TicketTableHeader({mode,allSelected,toggleAll}:{mode:WorkspaceMode;allSelected:boolean;toggleAll:()=>void}){return <div className="sbay-ticket-row sbay-ticket-row--header">{mode==='staff'?<><input aria-label="Select all tickets" checked={allSelected} onChange={toggleAll} type="checkbox"/><span/></>:null}<span>Title</span><span>Reply</span>{mode==='staff'?<span>Agent</span>:null}<span>Date</span></div>}

const parseDate=(value:string)=>new Date(value.includes('T')?value:value.replace(' ','T'));
const relativeDate=(value:string)=>{const seconds=Math.max(0,Math.floor((Date.now()-parseDate(value).getTime())/1000));if(seconds<60)return '1 minute ago';const minutes=Math.floor(seconds/60);if(minutes<60)return `${minutes} minute${minutes===1?'':'s'} ago`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours} hour${hours===1?'':'s'} ago`;const days=Math.floor(hours/24);if(days<30)return `${days} day${days===1?'':'s'} ago`;const months=Math.floor(days/30);if(months<12)return `${months} month${months===1?'':'s'} ago`;const years=Math.floor(days/365);return `${years} year${years===1?'':'s'} ago`};
const fullDate=(value:string)=>parseDate(value).toLocaleString(undefined,{month:'long',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});

function TicketDates({ticket}:{ticket:WorkspaceTicket}){const reply=ticket.last_reply_at||ticket.created_at;return <span className="sbay-ticket-dates"><time dateTime={reply} tabIndex={0} data-tooltip={`Replied:\n${fullDate(reply)}`}><b aria-hidden="true">☵</b>{relativeDate(reply)}</time><time dateTime={ticket.created_at} tabIndex={0} data-tooltip={`Opened:\n${fullDate(ticket.created_at)}`}><b aria-hidden="true">⊕</b>{relativeDate(ticket.created_at)}</time></span>}

interface Props{mode:WorkspaceMode;ticket:WorkspaceTicket;selected:boolean;toggle:()=>void;open:()=>void;showCategories:boolean;statusLabels:Record<string,string>}
export function TicketRow({mode,ticket,selected,toggle,open,showCategories,statusLabels}:Props){return <div className="sbay-ticket-row">{mode==='staff'?<><input aria-label={`Select ${ticket.subject}`} checked={selected} onChange={toggle} type="checkbox"/><span className="sbay-ticket-avatar">{ticket.customer_avatar_url?<img src={ticket.customer_avatar_url} alt=""/>:'◉'}</span></>:null}<button className="sbay-ticket-title" onClick={open}><strong>{ticket.subject} {ticket.customer_name?<small>by {ticket.customer_name}</small>:null}</strong>{ticket.latest_reply_excerpt?<small className="sbay-ticket-excerpt">{ticket.latest_reply_excerpt}</small>:null}<span><i>{statusLabels[ticket.status]??ticket.status}</i> #{ticket.track_id}{showCategories?` · ${ticket.category_name||'Uncategorized'}`:''} · {ticket.priority}{mode==='staff'&&ticket.tags?.map(tag=><em className="sbay-ticket-tag" style={{borderColor:tag.color??undefined}} key={tag.id}>{tag.name}</em>)}</span></button><span className="sbay-ticket-replies">{ticket.reply_count??0}{mode==='staff'&&ticket.needs_reply?<i className="sbay-need-reply">Need Reply</i>:null}{mode==='customer'&&ticket.has_support_reply?<i className="sbay-support-replied">Agent Replied</i>:null}</span>{mode==='staff'?<span>{ticket.agent_name||'Unassigned'}</span>:null}<TicketDates ticket={ticket}/></div>}
