import { FormEvent, useEffect, useState } from 'react';
import { apiGet, apiPost } from '../../api/client';
import { RichTextEditor } from '../../../shared/editor/RichTextEditor';

interface Options { customers:Array<{id:number;name:string;email:string}>; departments:Array<{id:number;name:string}>; }
interface Props { close:()=>void; created:(id:number)=>void; }

export function StaffTicketCreateModal({close,created}:Props){
  const [options,setOptions]=useState<Options|null>(null);const [customerId,setCustomerId]=useState('');const [subject,setSubject]=useState('');const [content,setContent]=useState('');const [departmentId,setDepartmentId]=useState('');const [priority,setPriority]=useState('normal');const [error,setError]=useState<string|null>(null);const [saving,setSaving]=useState(false);
  useEffect(()=>{apiGet<Options>('admin/tickets/create-options').then(setOptions).catch(reason=>setError(reason instanceof Error?reason.message:'Ticket creation options could not be loaded.'));},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError(null);try{const ticket=await apiPost<{id:number}>('admin/tickets/create-for-customer',{customer_id:Number(customerId),subject,content,department_id:Number(departmentId),priority});created(ticket.id);}catch(reason){setError(reason instanceof Error?reason.message:'Ticket could not be created.');}finally{setSaving(false);}};
  return <div className="sbay-staff-create-modal" role="dialog" aria-modal="true" aria-labelledby="sbay-create-ticket-title"><form onSubmit={submit}><header><div><small>Staff ticket creation</small><h2 id="sbay-create-ticket-title">Create Ticket for Customer</h2></div><button type="button" onClick={close} aria-label="Close">×</button></header>{error?<p role="alert">{error}</p>:null}{!options?<p>Loading customers…</p>:<><label>Customer<select required value={customerId} onChange={event=>setCustomerId(event.target.value)}><option value="">Select an existing customer…</option>{options.customers.map(customer=><option value={customer.id} key={customer.id}>{customer.name} — {customer.email}</option>)}</select></label><label>Subject<input required value={subject} onChange={event=>setSubject(event.target.value)}/></label><label>Department<select value={departmentId} onChange={event=>setDepartmentId(event.target.value)}><option value="">Support (default)</option>{options.departments.map(department=><option value={department.id} key={department.id}>{department.name}</option>)}</select></label><label>Priority<select value={priority} onChange={event=>setPriority(event.target.value)}><option value="normal">Normal</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label>Message<RichTextEditor value={content} onChange={setContent} disabled={saving}/></label><footer><button type="button" onClick={close}>Cancel</button><button disabled={saving||!customerId||!subject.trim()||!content.trim()}>{saving?'Creating…':'Create Ticket'}</button></footer></>}</form></div>;
}
